language: node_js

node_js:
  - 7
  - 6
  - 5

script:
  - yarn
  # - node ./internals/scripts/generate-templates-for-linting
  - yarn start:production

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'

cache:
  yarn: true
  directories:
    - node_modules
